# yaml-language-server: $schema=https://schema.infrahub.app/python-sdk/repository-config/latest.json
---
# TRANSFORMS
jinja2_transforms:
  - name: "device_cisco"
    description: "Template to generate startup configuration for Cisco devices"
    query: "device_info"
    template_path: "templates/device_cisco_config.tpl.j2"

artifact_definitions:
  - name: "Startup Config for Cisco devices"
    artifact_name: "startup-config"
    parameters:
      device: "name__value"
    content_type: "text/plain"
    targets: "cisco_devices"
    transformation: "device_cisco"

# GENERATORS
generator_definitions:
  - name: implement_site
    file_path: "generators/implement_site.py"
    targets: automated_sites
    query: site_information
    class_name: ImplementSiteGenerator
    parameters:
      site_name: "name__value"

# QUERIES
queries:
  - name: site_information
    file_path: "generators/site_information.gql"
  - name: device_info
    file_path: "templates/device_info.gql"
